#!/bin/bash
echo ''
echo '---------------------'
echo 'whoami'
whoami

# Jump to starting dir
echo ''
echo '---------------------'
echo 'Jump to starting dir'
cd /home/ec2-user

# Clone the repo
echo ''
echo '---------------------'
echo 'Clone the repo'
sudo yum -y install git
sudo git clone https://github.com/joshuakcockrell/byu-cs-462.git

# Download node
echo ''
echo '---------------------'
echo 'Download node'
wget -qO- https://raw.githubusercontent.com/xtuple/nvm/master/install.sh | sudo bash
. ~/.nvm/nvm.sh
nvm install node
node -v

# Route port 80 to 8000
echo ''
echo '---------------------'
echo 'Route port 80 to 8000'
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000

# NPM install
echo ''
echo '---------------------'
echo 'NPM install'
cd byu-cs-462
npm install

# Start server
echo ''
echo '---------------------'
echo 'Start server'
./start_server

