#!/bin/bash
echo ''
echo '---------------------'
echo 'whoami'
whoami

# Jump to starting dir
echo ''
echo '---------------------'
echo 'Jump to starting dir'
cd /home/ec2-user

# Route port 80 to 8000
echo ''
echo '---------------------'
echo 'Route port 80 to 8000'
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000

# Clone the repo
echo ''
echo '---------------------'
echo 'Clone the repo'
yum -y install git
git clone https://github.com/joshuakcockrell/byu-cs-462.git

# Run Rest as not root
echo ''
echo '---------------------'
echo 'Run Script as not root'
cd byu-cs-462


# Download node
echo ''
echo '---------------------'
echo 'Download node'
yum -y install nodejs npm --enablerepo=epel
# curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
# . ~/.nvm/nvm.sh
# nvm install node
node -v

# NPM install
echo ''
echo '---------------------'
echo 'NPM install'
npm install

# Start server
echo ''
echo '---------------------'
echo 'Start server'
./start_server



#su ec2-user ./user_data_script


