#!/bin/bash
echo ''
echo '---------------------'
echo 'whoami'
whoami

# Jump to starting dir
echo ''
echo '---------------------'
echo 'Jump to starting dir'
cd /home/ec2-user

# Route port 80 to 8000
echo ''
echo '---------------------'
echo 'Route port 80 to 8000'
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000

# Clone the repo
echo ''
echo '---------------------'
echo 'Clone the repo'
yum -y install git
git clone https://github.com/joshuakcockrell/byu-cs-462.git

# Run Rest as not root
echo ''
echo '---------------------'
echo 'Run Script as not root'
cd byu-cs-462
su ec2-user ./user_data_script


