#!/bin/bash
echo ''
echo '---------------------'
echo 'whoami'
whoami

# Jump to starting dir
echo ''
echo '---------------------'
echo 'Jump to starting dir'
cd /home/ec2-user

# Route port 80 to 8000
echo ''
echo '---------------------'
echo 'Route port 80 to 8000'
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8000

# # List redirects
# sudo iptables -t nat -L INPUT --line-numbers
# # Delete 1st redirect
# sudo iptables -t nat -D PREROUTING 1


# Clone the repo
echo ''
echo '---------------------'
echo 'Clone the repo'
yum -y install git
git clone https://github.com/joshuakcockrell/byu-cs-462.git
cd byu-cs-462

# Download node
echo ''
echo '---------------------'
echo 'Download node'
yum -y install nodejs npm --enablerepo=epel
node -v

# NPM install
echo ''
echo '---------------------'
echo 'NPM install'
npm install

# Grant permissions for standard user
sudo touch output.log
sudo chmod -R 777 /home/ec2-user/byu-cs-462/output.log
sudo touch db.json
sudo chmod -R 777 /home/ec2-user/byu-cs-462/db.json

# Start server
echo ''
echo '---------------------'
echo 'Start server'
./start_server



